site_name: Dysfunctinoal Lisp
site_url: https://example.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
    - 'Introduction': [Description: index.md]
    - 'Syntax': [Abstract: syntax_abstract.md, Grammar: syntax_grammar.md]
    - 'Tutorial': [Get Started: get_started.md, LCM Calculator: lcm_list.md]
    - 'Language': [Special Forms: special_forms.md, Predefined Functions: predefined_functions.md]

theme:
  name: readthedocs